### ISSUE TITLE
兄弟继续努力啊，看好这个项目

### ISSUE THREAD

**Issue by jiashiwen** [yametech/canal#7]

**Comment by withlin** [comment]
兄弟，不好意思啊，我们这一年都忙于做容器云了，忽视了redis-canal这块,canal这块你有用到生产上面么？

**Comment by jiashiwen** [comment]
我们有个项目现在是java写的，如果有了这个基础设施可以用go重写，你哪个公司的容器我也懂一点点

**Comment by jiashiwen** [comment]
我们项目刚开源https://github.com/TraceNature/redissyncer-server

**Comment by withlin** [comment]
嗯，你有试过我们的吧，我们的速度杠杠的

**Comment by jiashiwen** [comment]
回头试一下
